### ISSUE TITLE
Incorrect user or password

### ISSUE THREAD

**Issue by ianrossi** [chef/knife-vsphere#3]
Here is my configuration In the knife.rb file:

knife[:vsphere_host] = "host.domain.com"
knife[:vsphere_user] = "WINDOWSDOMAIN\username"
knife[:vsphere_pass] = "PASSWORD"
knife[:vsphere_dc] = "DATA-CENTER"

I am getting the error:
ERROR: RbVmomi::Fault: InvalidLogin: Cannot complete login due to an incorrect user name or password.

My question is:
How do I format the value for knife[:vsphere_user] ? When I log into the vSphere client in Windows, I login using WINDOWSDOMAIN\username. Should it be different here? I have also tried username@WINDOWSDOMAIN. We use NT Authentication to log on to vCenter.

Thanks.

**Comment by drahamim** [comment]
I am still getting this error.  I have tested that the credentials work. Is there anything I need to enable on the Vcenter side?

I have tried using Base64: obvuscation, Plain text, With and without DOMAIN\

**Comment by bhaliti** [comment]
username@domainname.com (whatever domain you are in) fixed the problem for me. I had to make sure my password did not have special characters, if it does you can shield it %Q("password")

I am very new to chef and wanted to share since I could not find a solution online.
