### ISSUE TITLE
ERROR: RuntimeError: expected ResourcePool, got Folder for field "pool" 

### ISSUE THREAD

**Issue by ianrossi** [chef/knife-vsphere#4]
Thanks for this gem!!

The error 

ERROR: RuntimeError: expected ResourcePool, got Folder for field "pool" 

is given when using the "knife vsphere vm clone command". However, the --resource-pool option is not set and is not listed as required in the help listing.

I had used the --resource-pool option on my first command, misunderstanding what a resource pool was in vSphere. However, we don't use resource pools in our deployment of vSphere. So, I removed it, but this error persists.

I also tried moving the --folder and --dest-folder options around in the command order, but not change.

Here is my command with the sensitive information removed:

knife vsphere vm clone NEWVMNAME \
--template OUR_TEMPLATE --datacenter OUR_DATACENTER --ssh-user root \
--ssh-password PASSWORD --datastore OUR_DATASTORE \
--folder _Templates --dest-folder Servers/Linux \
--start STARTVM \
--cspec "Ubuntu 10.04 (x64)" \
--run-list 'role[base],role[mediawiki_database_master]'

I also tried the command like this, but it returned the same error.

knife vsphere vm clone NEWVMNAME --template OUR_TEMPLATE --folder _Templates

Thanks again for this gem and thanks for looking at this.

Kind regards,

Ian D. Rossi

**Comment by henriquegontijo** [comment]
I was facing the same issue "wait_for_completion': CannotAccessVmComponent: A component of the virtual machine is not accessible on the host.".
So I created the pool and it worked for me:
$ knife vsphere vm clone test-chef --template <templatename> --datastore <dsname> --chostname <hostname> -f nimbus --dest-folder <folder> -VV --disable-customization --resource-pool <poolname>
