### ISSUE TITLE
Remove deprecated template_file and distro options

### ISSUE THREAD

**Issue by tas50** [chef/knife-vsphere#458]
The template and distro options were removed from chef-client and need to be removed from knife-vsphere as well.

**Comment by swalberg** [comment]
Hey Tim, I will have a look, thanks.

**Comment by tas50** [comment]
There's a nice example of how to add the warning via a proc here https://github.com/chef/knife-windows/pull/470/files/53ab4e9eb7df5ae5e834173a678005b91dff7994..6a01bec3232221be8f1bf4a8732797e6612193f0
