### ISSUE TITLE
upgrade ESX with chef

### ISSUE THREAD

**Issue by rushins** [chef/knife-vsphere#462]
### Versions:

* Version of knife-vsphere:
* Version of chef:

### Platform Details

* Version of vSphere: 6.0 to 6.5
* Version of ESXi: 6.0 to 6.5

### Scenario:

upgrade ESX 6.0 gto 6.5 using CHEF .
### Expected Result:

i would like to understand if this is doable . i mean chef automation with ESX release upgrade from version to version. we are currrently using VMWARE update manager which supports upgrade version to version.

**Comment by jjasghar** [comment]
The short of it is no, the underlying OS that ESXi runs doesn't have enough to have the chef client run successfully.

The best option if you need to do multiple is learn PowerCLI and use that to do things like this, but honestly the built in tooling of update manager is probably best.

This is really out of scope of knife-vsphere and i don't think it'll ever be in scope.

**Comment by swalberg** [comment]
Also wanted to add that the SOAP API we use isn't the same one that VUM uses. So even outside of Chef itself running on the host, it would need APIs that are out of scope for this gem. 

The code.vmware.com site does seem to have some examples using the update API and powercli.
