### ISSUE TITLE
knife vsphere vm execute fails with no program args

### ISSUE THREAD

**Issue by dsopscak** [chef/knife-vsphere#467]
### Versions:

* Version of knife-vsphere: 2.1.3
* Version of chef: 14.6.47

### Platform Details

* Version of vSphere: 6.5.0
* Version of ESXi: 5.5

### Scenario:

Run an arbitrary command on a VM to determine if the user it runs as exists.

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

C:\>knife vsphere vm execute skipdomtest --exec-user skipdomtest\Wallace --exec-passwd XXX -VV -- C:\Windows\System32\whoami.exe
INFO: Using configuration from Z:/.chef/knife.rb
DEBUG: value for config item folder:
DEBUG: value for config item vsphere_host: omadevivcss06.csgidev.com
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: devcsg\SVC_SelfProv
DEBUG: value for config item vsphere_pass: XXX
DEBUG: value for config item vsphere_pass: XXX
DEBUG: value for config item vsphere_pass: XXX
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: ODC_Self_Prov
C:/Users/sops01/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-vsphere-2.1.3/lib/chef/knife/vsphere_vm_execute.rb:56:in `run': undefined method `join' for "":String (NoMethodError)
Did you mean?  JSON
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.26-universal-mingw32/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.26-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.26-universal-mingw32/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.26-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.26-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.26-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:68:in `load'
        from C:/opscode/chefdk/bin/knife:68:in `<main>'
### Expected Result:

An authentication error or not
### Actual Result:

It throws an undef method error. If any argument is included it works as expected.

I believe the problem is related to the vsphere_vm_execute.rb file id'd in the stack trace. At line 46 the args variable is defaulted to an empty string if it's nil or empty. That causes the error at line 56 since join is undefined on a string object. I think it should be set to an empty array in that case. I've tested that change and it seems to fix it. I've never submitted a pull request to a chef project before. If this isn't already fixed before I get that figured out, I'll submit the proposed fix.

**Comment by swalberg** [comment]
Nice find! By all means please make a PR, reach out here if you have any problems with that. 

Sean
