### ISSUE TITLE
vm state --state suspended  may not be suspending

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/knife-vsphere#477]
### Versions:

* Version of knife-vsphere: 2.1.3
* Version of chef: 14.8.12

### Platform Details

* Version of vSphere:  6.5.0.23000
* Version of ESXi: 6.5.0, 10884925 

### Scenario:

I'm hoping to suspend a VM via 'vm state VMName --state suspended'

### Please paste the command and output (run with `-VV`). Don't forget to X out any passwords or sensitive information:

All values - hostnames, usernames, passwords, paths - were as expected.  Other commands (eg cloning a host) use the same creds and details to great effect.
```
knife vsphere vm state vmname --state suspended -VV
INFO: Using configuration from /home/xxxxxxx/chef-repo/knife/prod/knife.rb
DEBUG: value for config item vsphere_host: xxxxxxx
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xxxxxxx\xxxxxxxxx
DEBUG: value for config item vsphere_pass: base64:xxxxxxxxxx=
DEBUG: value for config item vsphere_pass: base64:xxxxxxxxxx=
DEBUG: value for config item vsphere_pass: base64:xxxxxxxxxx=
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item wait_port:
```

### Expected Result:

I'm *hoping* that `--state suspended` is intended for suspending VMs (and not, say, simulating a power event to move a VM to suspended via an OS command)

So I'm hoping to see the VM transition to a suspended state via that invocation.

### Actual Result:

Sadly, the command completes without error, but the VM doesn't change state as hoped.

**Comment by swalberg** [comment]
Hi, do you get any kind of output after `DEBUG: value for config item wait_port:
`? From [the code](https://github.com/chef/knife-vsphere/blob/2d10d3404a44f0db3e18ee0419f1bea901424de3/lib/chef/knife/vsphere_vm_state.rb#L97) I'd expect a `"Suspended virtual machine #{vmname}"`.

I don't use this command myself and the implementation predates me, but my reading of the docs are that this should do what you're hoping for.

**Comment by bby-bishopclark** [comment]
No, nothing at all -- and from that code URL I'd expect *some* kind of word, but the empty wait_port setting is the last line reported to output -- no other message either way.

But that code gives me an idea, and Oh, Look!

````
knife vsphere vm state xxxxxxx --state suspend
:
Suspended virtual machine xxxxxxx
:
````

So it's just a documentation issue:  suspend works, and suspend**ed** silently fails (and I'll bet it leaves the switch statement at L105 without matching; argh)

I bet there's potential to improve the behaviour, maybe with a 'default' case as well in there, as well as a doc fix, but it's really my own fault for ignoring the source!  

Many thanks for the quick response.

**Comment by swalberg** [comment]
Good catch! Will log this as a defect to fix.

**Comment by bby-bishopclark** [comment]
There.  Ideally I'll stop forgetting the syntax, reading the docs and forgetting this was an issue, and getting more unsuspended machines to confuse my day.  The facepalms are many and mighty.  I don't have the chops/time to hammer at the code change today, but at least I can trivially mod the docs.

**Comment by bby-bishopclark** [comment]
I can't test this, as we're not moving to Chef-15 over licensing concerns.  Is the change tiny enough that we can let it go without confirmation?

**Comment by swalberg** [comment]
Sorry, which change? #481? Yea it's small.

We're staying on Chef 14 as well... Knife just uses the public gems; I didn't think it hits any licensing concerns for running locally.

**Comment by swalberg** [comment]
This was fixed to handle both.
