### ISSUE TITLE
Not able to run knife vsphere command 

### ISSUE THREAD

**Issue by n33ti** [chef/knife-vsphere#479]
# Describe the problem
Facing the Error:  C:/Users/npriyasinha/.chef/knife.rb:1:in `<main>': undefined local variable or method `knife' for main:Object (NameError)

## Software Version
Windows 10

![image](https://user-images.githubusercontent.com/52991838/66110308-26eed000-e5e4-11e9-8f15-7aca02169e99.png)

**Comment by swalberg** [comment]
Hi, does `knife` work outside of that directory? Do you have ChefDK installed, and if so, which version? Are you intending to develop with this gem or are you trying to use it?

If you're trying to use the gem, typically `chef gem install knife-vsphere` or simply `gem install knife-vsphere` if you're not using ChefDK is enough. You don't need to download the source code and should use the public gem distribution.

**Comment by n33ti** [comment]
Hi, thanks for the reply. Yes I have installed chefDK version 4.4.27
![image](https://user-images.githubusercontent.com/52991838/66141943-3a209080-e622-11e9-8eca-d746429b3f65.png)

I have used chef gem install knife-vsphere .

I didn't download the source code. I just created a knife.rb file inside .chef folder. The error says that it cannot recognize knife method or variable.. Do I have to import knife (using 'require') in my ruby file? 
My knife.rb file is same as what is instructed in the  README.md. Am I doing anything wrong?

**Comment by swalberg** [comment]
I'd suggest deleting it and starting off with [knife configure](https://docs.chef.io/knife_configure.html). My file doesn't have any requires, but it has `knife` and some other Chef configuration, so I sense that something else is missing.

**Comment by n33ti** [comment]
Okay. I deleted that ruby file and ran knife configure (which I had not done before). I am facing this error now. Could you please help me.

![image](https://user-images.githubusercontent.com/52991838/66145099-ba95c000-e627-11e9-9800-f2172b93b1f8.png)

**Comment by swalberg** [comment]
I think you now have some conflicting plugins. `knife-vcenter` wants an older version of `knife-cloud`. Deleting `knife-vcenter` will get you past it, but if you need it, you will want to look at downgrading `knife-cloud` to a 1.x version.

**Comment by swalberg** [comment]
`gem uninstall knife-vcenter`
or
`gem uninstall knife-cloud; gem install knife-cloud -v 1.2.3`

look like your options (haven't tried)

**Comment by n33ti** [comment]
HI sorry for the delay. I reinstalled chefDK and then installed knife-vsphere. Now also I am facing the same conflicting error on running knife configure; so I tried uninstalling knife-cloud, but it says knife-vcloud is not installed.

![image](https://user-images.githubusercontent.com/52991838/66150002-ee75e300-e631-11e9-9e63-ac2dcca57ae8.png)

**Comment by swalberg** [comment]
Oh, try `chef gem` instead of just `gem`.

**Comment by n33ti** [comment]
I unistalled knife-cloud but now cannot install it :(

![image](https://user-images.githubusercontent.com/52991838/66151490-0c911280-e635-11e9-8ae5-53624d2de8b6.png)

**Comment by swalberg** [comment]
Hm, something seems to be trying to load `knife-cloud v 2.0.3`. Do any other knife commands work?

**Comment by n33ti** [comment]
I didn't check earlier. No  knife command is running:

![image](https://user-images.githubusercontent.com/52991838/66180405-928b7880-e68a-11e9-9077-b877d2ab3395.png)

So I am starting all again. I am reinstalling chefDK. Could please tell me what should I do next? (I am very new to all this)

**Comment by n33ti** [comment]
So starting fresh, I installed chefDK and then ran chef gem install knife-vsphere. After that am I supposed run gem install knife-vsphere as well?

**Comment by swalberg** [comment]
Hi, no, prefixing it with `chef` will install it into the chef managed gem directory. What do you get now? (Did you also do the `knife configure`?)

**Comment by n33ti** [comment]
Hi, okay. I am still facing errors on running knife configure:

![image](https://user-images.githubusercontent.com/52991838/66265556-4b41eb00-e836-11e9-8d8a-5a0861a41a50.png)

**Comment by swalberg** [comment]
Hm, I'm not really sure what's going on. I'm not too familiar with the inner workings of Knife other than what it takes to make this plugin. Wondering if you might get better help on the [Chef community slack](https://community-slack.chef.io)? 

Another thought, the latest ChefDK comes with knife-vsphere already installed, does it not work out of the box without installing any gems?

**Comment by tas50** [comment]
You're running into deps that can't be resolved due to the way that appbundler work. You'll want to install the latest Chef Workstation (DK's replacement) which comes with this gem built in.
