### ISSUE TITLE
IP and hostname not assigned if using open-vm-tools

### ISSUE THREAD

**Issue by yangpeng-chn** [chef/knife-vsphere#480]
# Version:

open-vm-tools-10.0.5-2.el7.x86_64
open-vm-tools-desktop-10.0.5-2.el7.x86_64
knife-vsphere (3.0.1)

# Environment:
OS in template: RHEL7.3 64 bit

```
knife vsphere vm clone EXAMPLE \
--ccpu 4 \
--cdomain <mydomain> \
--cgw 10.xx.xx.1 \
--chostname example \
--cips 10.xx.xx.195/24 \
--cmacs xx:xx:xx:xx:xx:x \
--cram 8 \
--ctz <mytimezone> \
--cvlan <myvlan> \
--datastorecluster <mycluster> \
--dest-folder <myfolder> \
--resource-pool <mypool> \
--start \
--template <template_with_rhel7.3_and_open_vm_tools> -f <myfolder>
```

# Scenario:

The cpu, memory and mac addresses can be set in the new VM with the command above, but the ip address and hostname remain the same with what was in the template.

# Steps to Reproduce:

Use open-vm-tools in the template and run the command above.

# Expected Result:

Hostname should be `example`, ip should be `10.xx.xx.195`

# Actual Result:

Hostname is `localhost`, ip is `<ip_in_the_template>`.

I tried the same command with the template where vmware-tools (`VMwareTools-10.0.9-3917699.tar.gz`) was installed but not open-vm-tools.

**Comment by yangpeng-chn** [comment]
Just found similar issue in https://github.com/chef/knife-vsphere/issues/450#issuecomment-431810227
I tried below and it seems to be working!!
1. Disable selinux (vi /etc/selinux/config, set SELINUX=disabled) and reboot
2. Install perl

**Comment by swalberg** [comment]
Hm, I'm surprised it worked with vmware-tools in the first place. Glad it's fixed, and thanks for your troubleshooting and followup!

**Comment by yangpeng-chn** [comment]
I believe the reason it worked with VMware-tools is because to install VMWare-tools, I had to install Perl which means the Perl is the key here. Actually I noticed there is a description about creating the template for clone in Wiki tab of this repo, it would be great if you could add the link to that page in the readme as I noticed it’s not only me who asked similar question here.

**Comment by bby-bishopclark** [comment]
Note that although perl is required for vmware-tools, and despite a perfect mechanism existing in RPM to pull perl in exactly where needed, the RedHat team has declined to add it as a dependency on the sub-package which requires it.

Keep the vmware-tools <-> perl dependency in your mind, and don't forget !
