### ISSUE TITLE
clone gives Exception: NameError: undefined local variable or method `connection' 

### ISSUE THREAD

**Issue by bbco-i** [chef/knife-vsphere#495]
Trying to automate VMware ESX 6.5 VM deployments with: 
   knife vsphere vm clone $myvm --template $mytemplate --cips $myIPs --chostname "$myhostname" --bootstrap false -VVV

This should prompt for the ESX host password, but instead outputs:
Exception: NameError: undefined local variable or method `connection' for #<Chef::Knife::VsphereVmClone:0x0000000002cd5440>

knife.rb is setup with these 4 details: host IP, user, dc and :vsphere_insecure. Other knife vsphere commands are working correctly, starting with a prompt for the password. 

Chef Development Kit Version: 3.7.23
chef-client version: 14.10.9
knife-vsphere (4.0.8, 2.1.1)
 chef gem  2.7.8
on Ubuntu 16.04

**Comment by bbco-i** [comment]
I should mention too that "knife vsphere template list" returns nothing. I created a template earlier but it doesnt find it. Im thinking here it needs to refresh the connection to the esx host somehow, its using configuration from /home/$myuser/knife.rb

**Comment by swalberg** [comment]
Hi, can you provide the full output including stack trace please? `XXXX` out any sensitive stuff.

Are your templates in a folder? If so, the `knife vsphere template list` command needs you to pass the name of the folder in with `-f` or `--folder`. It's not a recursive search.

**Comment by swalberg** [comment]
Also if your template is in a folder, the clone command should also pass that folder with `-f` or `--folder`. You'll probably also want to use `--dest-folder` to tell it where to put the resulting VM otherwise it looks like it goes in the template directory.

**Comment by swalberg** [comment]
Did you say you tried it with version 2.1.1? I just tried 4.0.9 and I get the same error as you if I use Chef 14. If I depend on Chef 15 I get the password prompt, but didn't try any further since we are not licensed.

I'd imagine 2.1.1 would work since it is from before the Chef 15 changes.

**Comment by bbco-i** [comment]
knife-vsphere is at 4.0.8. I just upgraded Chef now to 14.16 (latest available) and I get to the password prompt, thanks! But now its back to "Could not find template". 
DEBUG: value for config item source_vm: XXX
FATAL: Could not find template XXX
Is there some parameter for knife.rb where I can give it the vCenter Server address in addition to the host address? Template information is stored in vCenter, ESX doesnt see templates, only vms.

**Comment by swalberg** [comment]
You should point to the vcenter server for everything. It'll take care of putting it on the right server. `--resource-pool` can take a cluster or resource pool if you want to put the VM in a particular spot.

**Comment by bbco-i** [comment]
Getting somewhere now :) I changed knife.rb to use vcenter address. vCenter server and the host have 2 different login credentials; my command is confusing chef:  Cannot complete login due to an incorrect user name or password. I need to seperate out these 2 credentials if possible: 
knife.rb credentials: 
knife[:vsphere_host] = "xxx"
knife[:vsphere_user] = "xxx@vsphere.local"
knife[:vsphere_dc] = "xxx"
knife[:vsphere_insecure] = true

And credentials I pass in the command for the host: 
   knife vsphere vm clone XXX --template XXX --cips XXXX --chostname "XXX" --bootstrap false --vshost xxx --vsuser xxx --vspass xxx --vsinsecure -VVV

**Comment by bbco-i** [comment]
Just to clarify previous comment: 
In knife.rb:  knife[:vsphere_host] = "this is vcenter server address now" 
and command --vshost has host where I want the vm built, vsuser and vspass have credentials for the host.

**Comment by swalberg** [comment]
I'm not a vmware admin so I'm not sure of all the options available or if I'm using the right terms. This gem is made for the model where you have a vcenter service that manages all your hosts. All the API operations go to vcenter and this gem never talks to an individual host when cloning.

If you want to make sure the VM goes on a particular host, there are some [placement options](https://github.com/chef/knife-vsphere#vmware-options) but that's still telling Vcenter to do everything. Under the hood it's really one connection to Vcenter -- first we read some objects such as finding the reference to the template, and then issue one big API call that clones the VM and places it. But in the end, the hosts are just capacity that's managed by Vcenter and there's no need to talk to an individual host.

So I'm afraid there's no way to have two separate logins since it's all assumed to be one system.

**Comment by bbco-i** [comment]
The trick is to keep it simple- this command is now building the VM on the ESX host that I want it on: 
knife vsphere vm clone xxx --template xxx --cips xxx --chostname "xxx" --bootstrap false --resource-pool "$ESXhost"  -VVV
Thank you very much for all the help @swalberg :)

**Comment by swalberg** [comment]
Ah, cool. TIL that `--resource-pool` will also accept a host. Glad you got it working!
